from tensorflow.keras.applications.vgg16 import preprocess_input as vgg16_preprocessing
from tensorflow.keras.applications.resnet_v2 import preprocess_input as resnet_v2_preprocessing
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet50_preprocessing
from tensorflow.keras.applications.efficientnet import preprocess_input as efficientnet_preprocessing
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_v2_preprocessing
from src.train import test_trained_model


val_path = '/home/ivanz/Desktop/chest_xray_data_and_models/data_balanced/val'

# 1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/1_conv_layer_filters_32_kernel_3_3_stride_1_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/2_conv_layers_filters_32_64_kernel_3_3_stride_1_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/3_conv_layers_filters_32_64_128_kernel_3_3_stride_1_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/4_conv_layers_filters_32_64_128_256_kernel_3_3_stride_1_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_max_pool/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=8)

# efficientnet_b6_pretrained_encoder_dense_and_batch_norm_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b6_pretrained_encoder_dense_and_batch_norm_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b6_pretrained_encoder_dense_and_batch_norm_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, efficientnet_preprocessing, batch_size=32)

# efficientnet_b6_pretrained_encoder_dense_layer_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b6_pretrained_encoder_dense_layer_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b6_pretrained_encoder_dense_layer_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, efficientnet_preprocessing, batch_size=32)

# efficientnet_b7_pretrained_encoder_dense_and_batch_norm_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b7_pretrained_encoder_dense_and_batch_norm_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b7_pretrained_encoder_dense_and_batch_norm_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, efficientnet_preprocessing, batch_size=32)

# efficientnet_b7_pretrained_encoder_dense_layer_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b7_pretrained_encoder_dense_layer_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/efficientnet_b7_pretrained_encoder_dense_layer_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, efficientnet_preprocessing, batch_size=32)

# mobilenet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/mobilenet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/mobilenet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# mobilenet_v2_pretrained_encoder_dense_layer_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/mobilenet_v2_pretrained_encoder_dense_layer_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/mobilenet_v2_pretrained_encoder_dense_layer_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# resnet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet_v2_pretrained_encoder_dense_and_batch_norm_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet_v2_preprocessing, batch_size=32)

# resnet_v2_pretrained_encoder_dense_layer_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet_v2_pretrained_encoder_dense_layer_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet_v2_pretrained_encoder_dense_layer_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet_v2_preprocessing, batch_size=32)

# resnet50_pretrained_encoder_dense_and_batch_norm_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet50_pretrained_encoder_dense_and_batch_norm_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet50_pretrained_encoder_dense_and_batch_norm_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet50_preprocessing, batch_size=32)

# resnet50_pretrained_encoder_dense_layer_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet50_pretrained_encoder_dense_layer_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/resnet50_pretrained_encoder_dense_layer_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet50_preprocessing, batch_size=32)

# sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_1_layer_2_units_vgg16_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_vgg16_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_1_layer_2_units_vgg16_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, vgg16_preprocessing, batch_size=32)

# sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_2_layers_2_4_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_3_layers_2_4_8_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_3_layers_2_4_8_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_3_layers_2_4_8_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_4_layers_2_4_8_16_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_4_layers_2_4_8_16_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_4_layers_2_4_8_16_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_5_layers_2_4_8_16_32_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_5_layers_2_4_8_16_32_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_5_layers_2_4_8_16_32_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_6_layers_2_4_8_16_32_64_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_6_layers_2_4_8_16_32_64_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_6_layers_2_4_8_16_32_64_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_7_layers_2_4_8_16_32_64_128_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_8_layers_2_4_8_16_32_64_128_256_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing_dropout.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/sequential_dense_9_layers_2_4_8_16_32_64_128_256_512_units_mobile_net_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# test_architecture_from_kaggle_1_efficientnet_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_efficientnet_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_efficientnet_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, efficientnet_preprocessing, batch_size=32)

# test_architecture_from_kaggle_1_mobilenet_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_mobilenet_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_mobilenet_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, mobilenet_v2_preprocessing, batch_size=32)

# test_architecture_from_kaggle_1_resnet_v2_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_resnet_v2_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_resnet_v2_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet_v2_preprocessing, batch_size=32)

# test_architecture_from_kaggle_1_vgg16_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_vgg16_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_architecture_from_kaggle_1_vgg16_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, vgg16_preprocessing, batch_size=32)

# test_models_on_training_data_resnet50_preprocessing.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_models_on_training_data_resnet50_preprocessing/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/test_models_on_training_data_resnet50_preprocessing/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, resnet50_preprocessing, batch_size=32)

# vgg16_pretrained_encoder_dense_layers_trainable.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/vgg16_pretrained_encoder_dense_layers_trainable/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/vgg16_pretrained_encoder_dense_layers_trainable/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, vgg16_preprocessing, batch_size=32)

# vgg16_reconstructed_architecture.py

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/vgg16_reconstructed_architecture/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/vgg16_reconstructed_architecture/classification_report_and_confusion_matrix_on_val_data'

test_trained_model(model_path, save_path, val_path, vgg16_preprocessing, batch_size=32)