from src.train import test_trained_model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input as mobilenet_v2_preprocessing

test_path = '/home/ivanz/Desktop/chest_xray_data_and_models/data_balanced/test'

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_batch_norm/classification_report_and_confusion_matrix_on_test_data'

test_trained_model(model_path, save_path, test_path, mobilenet_v2_preprocessing, batch_size=16)

# 5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout

model_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/model.h5'
save_path = '/home/ivanz/Desktop/chest_xray_data_and_models/trained_models/balanced_models/5_conv_layers_filters_32_64_128_256_512_kernel_3_3_stride_1_mobile_net_v2_preprocessing_dropout/classification_report_and_confusion_matrix_on_test_data'

test_trained_model(model_path, save_path, test_path, mobilenet_v2_preprocessing, batch_size=16)